language: node_js
node_js:
  - "stable"

services:
  - docker

cache:
  directories:
    - "node_modules"
install:
  - npm install

jobs:
  include:
    - stage: build docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t time-manager-api .
        - docker images
        - docker tag time-manager-api $DOCKER_USERNAME/time-manager-api
        - docker push $DOCKER_USERNAME/time-manager-api